name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare mkdocs
        run: .github/workflows/docs_prepare.sh

      - name: Deploy documentation
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}